### PR TITLE
Implemented IDXGIOutput5

### PR DESCRIPTION
**Pull request by GNUDimarik**
Updated more optimized screen capture for screen without HW Acceleration

### CODE REVIEW

**Comment by GNUDimarik** [comment]
@m4rkoup please review the change

**Comment by m4rkoup** [comment]
@GNUDimarik preliminar in-house testing gave these results:

**Issues**:

The mouse and keyboard stop responding to proper commands
- getting some strange keyboard issues, it stops working
- mouse does not respond to clicks.

Mouse cursor still works.

Requires a VM reboot to fix it.

**How to reproduce?**

Seems to occur after I start and stop a game, not every time though. 

*Edit*: all you have to do is connect and disconnect several times. Eventually your mouse and keyboard will stop working correctly. Only restart will fix.

**Comment by m4rkoup** [comment]
The reason for the strange behavior with keyoboard was found. It happens when you quit moonlight session, with CTRL + ALT + SHIFT + Q. It seems some of the keyboards keeps active. I´ll try to introduce a fix for this.

**Comment by m4rkoup** [comment]
After some testing, I'm only seeing the problem with Moonlight PC v3.0.0.
If I do use Moonlight PC v2.2.0, the error doesn't happen.

**Review by m4rkoup — APPROVED** [review]
Since the error with keyboard is cause by recent version of moonlight, and testing went well, this PR is approved.

**Pull request merged**
